[package]
name = "math-eval-jit"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift = "0.116.1"
cranelift-codegen = "0.116.1"
cranelift-jit = "0.116.1"
cranelift-module = "0.116.1"
cranelift-native = "0.116.1"
meval = "0.2.0"
thiserror = "2.0.11"
